### ISSUE TITLE
Panic on unconventional fractional links

### ISSUE THREAD

**Issue by kaushalmodi** [wjdp/htmltest#101]
Hello,

You can find the panic log here: https://travis-ci.org/kaushalmodi/nim-nightly-docs/builds/428903236#L608

It panics when it comes across this link: https://kaushalmodi.github.io/nim-nightly-docs/system.html#+%,IntMax32,IntMax32

When testing, you may also ensure that these links don't cause panic too:

- https://kaushalmodi.github.io/nim-nightly-docs/system.html#-%,IntMax32,IntMax32
- https://kaushalmodi.github.io/nim-nightly-docs/system.html#*%,IntMax32,IntMax32
- https://kaushalmodi.github.io/nim-nightly-docs/system.html#/%,IntMax32,IntMax32
- https://kaushalmodi.github.io/nim-nightly-docs/system.html#%%,IntMax32,IntMax32

(That whole page might serve as a good test case.)

**Comment by wjdp** [comment]
Popped these links in a test case they do indeed cause a problem.

```
=== RUN   TestIssue101
--- FAIL: TestIssue101 (0.00s)
panic: parse https://kaushalmodi.github.io/nim-nightly-docs/system.html#+%,IntMax32,IntMax32: invalid URL escape "%,I" [recovered]
	panic: parse https://kaushalmodi.github.io/nim-nightly-docs/system.html#+%,IntMax32,IntMax32: invalid URL escape "%,I"

goroutine 248 [running]:
testing.tRunner.func1(0xc0004f2600)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x6d47e0, 0xc0014f4150)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/wjdp/htmltest/output.CheckErrorPanic(0x79da20, 0xc0014e2b40)
	/home/will/local/htmltest/output/error.go:22 +0x86
github.com/wjdp/htmltest/htmldoc.NewReference(0xc0014dcc80, 0xc0014e8930, 0xc000e4a230, 0x4f, 0xc0014f2868)
	/home/will/local/htmltest/htmldoc/reference.go:34 +0x109
github.com/wjdp/htmltest/htmltest.(*HTMLTest).checkLink(0xc0014c9d40, 0xc0014dcc80, 0xc0014e8930)
	/home/will/local/htmltest/htmltest/check-link.go:33 +0x1a0
github.com/wjdp/htmltest/htmltest.(*HTMLTest).testDocument(0xc0014c9d40, 0xc0014dcc80)
	/home/will/local/htmltest/htmltest/htmltest.go:203 +0x193
github.com/wjdp/htmltest/htmltest.Test(0xc0014e27e0, 0x1e, 0xc0014e27e0, 0x4dc5128f42af)
	/home/will/local/htmltest/htmltest/htmltest.go:139 +0x948
github.com/wjdp/htmltest/htmltest.tTestFile(0x751824, 0x1e, 0x5b9d86b7)
	/home/will/local/htmltest/htmltest/test_helpers_test.go:51 +0x43
github.com/wjdp/htmltest/htmltest.TestIssue101(0xc0004f2600)
	/home/will/local/htmltest/htmltest/check-link_test.go:624 +0x36
testing.tRunner(0xc0004f2600, 0x761610)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x353
FAIL	github.com/wjdp/htmltest/htmltest	4.810s
```

**Comment by wjdp** [comment]
Digging into this: this error is from golang's net/url package. It's upset about the use of percent encoding in the URL. This works in the browser but is likely incorrect per spec (in this case an RFC).
