### ISSUE TITLE
Go panics when control characters present in URL

### ISSUE THREAD

**Issue by wjdp** [wjdp/htmltest#118]
We should do better.

See https://github.com/wjdp/htmltest/pull/117
See https://github.com/golang/go/blob/7b62e984d941c753e7fb20f8b59a49acf62c88a7/src/net/url/url.go#L516

```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot"  />
```

```
=== RUN   TestImageSrcDataURI
--- FAIL: TestImageSrcDataURI (0.00s)
panic: parse data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
9TXL0Y4OHwAAAABJRU5ErkJggg==: net/url: invalid control character in URL [recovered]
	panic: parse data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
9TXL0Y4OHwAAAABJRU5ErkJggg==: net/url: invalid control character in URL
goroutine 46 [running]:
testing.tRunner.func1(0xc0004b8900)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:792 +0x6a7
panic(0x854220, 0xc000627770)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/panic.go:513 +0x1b9
github.com/wjdp/htmltest/output.CheckErrorPanic(0x93b780, 0xc0006558c0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/output/error.go:22 +0xd2
github.com/wjdp/htmltest/htmldoc.NewReference(0xc000670b80, 0xc000255730, 0xc0004d82d0, 0x8c, 0xc00065ef28)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmldoc/reference.go:34 +0x18e
github.com/wjdp/htmltest/htmltest.(*HTMLTest).checkImg(0xc0004bcb40, 0xc000670b80, 0xc000255730)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/check-img.go:15 +0x16e
github.com/wjdp/htmltest/htmltest.(*HTMLTest).testDocument(0xc0004bcb40, 0xc000670b80)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:211 +0x49c
github.com/wjdp/htmltest/htmltest.Test(0xc000654f60, 0x28, 0xc000654f60, 0x0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:139 +0xd3b
github.com/wjdp/htmltest/htmltest.tTestFile(0x8d99af, 0x28, 0x0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/test_helpers_test.go:51 +0x51
github.com/wjdp/htmltest/htmltest.TestImageSrcDataURI(0xc0004b8900)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/check-img_test.go:137 +0x44
testing.tRunner(0xc0004b8900, 0x8e4e80)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:878 +0x65a
FAIL	github.com/wjdp/htmltest/htmltest	1.459s
```

**Comment by wjdp** [comment]
Test `TestImageSrcDataURI` present and does not fail. Either not a problem or have already fixed.
