### ISSUE TITLE
Panic on invalid url in href (contains braces)

### ISSUE THREAD

**Issue by xadcoh** [wjdp/htmltest#122]
Hi!

```
htmltest -v
htmltest 0.10.3
2019-04-24T15:54:40Z
```

I believe this issue related to go net/url package, but I'd like to share it with you.

If `a href` contains invalid url like:
`<a href="(https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.security.doc/GUID-41E5E52E-A95B-4E81-9724-6AD6800BEF78.html)"`

program will crash with:

```
goroutine 1 [running]:
github.com/wjdp/htmltest/output.CheckErrorPanic(0x790b20, 0xc0007d26c0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/output/error.go:22 +0x86
github.com/wjdp/htmltest/htmldoc.NewReference(0xc00012de80, 0xc0009c35e0, 0xc000022300, 0x7e, 0xc0009d8748)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmldoc/reference.go:34 +0x109
github.com/wjdp/htmltest/htmltest.(*HTMLTest).checkLink(0xc0000d8d80, 0xc00012de80, 0xc0009c35e0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/check-link.go:33 +0x1a0
github.com/wjdp/htmltest/htmltest.(*HTMLTest).testDocument(0xc0000d8d80, 0xc00012de80)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:203 +0x193
github.com/wjdp/htmltest/htmltest.(*HTMLTest).testDocuments(0xc0000d8d80)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:182 +0x6a
github.com/wjdp/htmltest/htmltest.Test(0xc000011a40, 0x1, 0x1, 0x49)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:142 +0x8fb
main.run(0xc000011a40, 0xc000011a40)
	/home/travis/gopath/src/github.com/wjdp/htmltest/main.go:159 +0x1e8
main.main()
	/home/travis/gopath/src/github.com/wjdp/htmltest/main.go:66 +0x298
```

**Comment by wjdp** [comment]
Thanks, will look into

**Comment by wjdp** [comment]
Now returns

```
bad reference: "parse \"(https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.security.doc/GUID-41E5E52E-A95B-4E81-9724-6AD6800BEF78.html)\": first path segment in URL cannot contain colon" --- href_brackets.html --> <nil>
```

Seems upstream have fixed this. Unit test added.
