### ISSUE TITLE
Switch to single file mode when given a path to a file rather than a directory

### ISSUE THREAD

**Issue by wjdp** [wjdp/htmltest#34]
Output when pointed to a file:

```
htmltest started at 11:05:54 on corrupt.html
========================================================================
panic: discoverRecurse encountered a file: .

goroutine 1 [running]:
panic(0x689f60, 0xc4201a4ea0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/wjdp/htmltest/htmldoc.(*DocumentStore).discoverRecurse(0xc42011a540, 0x6e853c, 0x1)
	/home/will/go/src/github.com/wjdp/htmltest/htmldoc/document_store.go:92 +0x8f2
github.com/wjdp/htmltest/htmldoc.(*DocumentStore).Discover(0xc42011a540)
	/home/will/go/src/github.com/wjdp/htmltest/htmldoc/document_store.go:40 +0x40
github.com/wjdp/htmltest/htmltest.Test(0xc4201a60c0, 0x1)
	/home/will/go/src/github.com/wjdp/htmltest/htmltest/htmltest.go:69 +0x6ab
main.run(0xc4201a60c0, 0xc4201a60c0)
	/home/will/go/src/github.com/wjdp/htmltest/main.go:126 +0x2e2
main.main()
	/home/will/go/src/github.com/wjdp/htmltest/main.go:60 +0x1d0
```

Output when pointed to nothing:

```
htmltest started at 11:06:22 on opdksopwkd
========================================================================
panic: open opdksopwkd: no such file or directory

goroutine 1 [running]:
panic(0x689f60, 0xc4201a4ea0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/wjdp/htmltest/output.CheckErrorPanic(0x821380, 0xc4201a6210)
	/home/will/go/src/github.com/wjdp/htmltest/output/error.go:22 +0x93
github.com/wjdp/htmltest/htmldoc.(*DocumentStore).discoverRecurse(0xc42011a540, 0x6e853c, 0x1)
	/home/will/go/src/github.com/wjdp/htmltest/htmldoc/document_store.go:62 +0x15c
github.com/wjdp/htmltest/htmldoc.(*DocumentStore).Discover(0xc42011a540)
	/home/will/go/src/github.com/wjdp/htmltest/htmldoc/document_store.go:40 +0x40
github.com/wjdp/htmltest/htmltest.Test(0xc4201a60c0, 0x1)
	/home/will/go/src/github.com/wjdp/htmltest/htmltest/htmltest.go:69 +0x6ab
main.run(0xc4201a60c0, 0xc4201a60c0)
	/home/will/go/src/github.com/wjdp/htmltest/main.go:126 +0x2e2
main.main()
	/home/will/go/src/github.com/wjdp/htmltest/main.go:60 +0x1d0
```

The cli package should test the path before passing through to htmltest and make adjustment if it is a file rather than a directory. If the path does not resolve a suitable error message should show.

**Comment by wjdp** [comment]
Done in 930b14b033eeef3769c909c44075b61b6030764b
