### ISSUE TITLE
segfault in Document.Parse htmlMutex

### ISSUE THREAD

**Issue by miltador** [wjdp/htmltest#59]
Caught this panic on our Ubuntu Linux build server using latest (0.4.1) binary release:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x50e756]

goroutine 1 [running]:
github.com/wjdp/htmltest/htmldoc.(*Document).Parse(0x0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmldoc/document.go:47 +0x26
github.com/wjdp/htmltest/htmldoc.(*Document).IsHashValid(0x0, 0xc427267419, 0x22, 0xc4200b7800)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmldoc/document.go:105 +0x2b
github.com/wjdp/htmltest/htmltest.(*HTMLTest).checkInternalHash(0xc4200b7680, 0xc4272c07b0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/check-link.go:284 +0xbb
github.com/wjdp/htmltest/htmltest.(*HTMLTest).checkInternal(0xc4200b7680, 0xc4272c07b0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/check-link.go:258 +0xe9
github.com/wjdp/htmltest/htmltest.(*HTMLTest).checkLink(0xc4200b7680, 0xc4203becb0, 0xc42727c5b0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/check-link.go:84 +0x3d4
github.com/wjdp/htmltest/htmltest.(*HTMLTest).testDocument(0xc4200b7680, 0xc4203becb0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:146 +0x165
github.com/wjdp/htmltest/htmltest.(*HTMLTest).testDocuments(0xc4200b7680)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:130 +0x69
github.com/wjdp/htmltest/htmltest.Test(0xc420019fb0, 0x1)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:93 +0x771
main.run(0xc420019fb0, 0x7ffd07310b5e)
	/home/travis/gopath/src/github.com/wjdp/htmltest/main.go:154 +0x29e
main.main()
	/home/travis/gopath/src/github.com/wjdp/htmltest/main.go:62 +0x1c1
Process exited with code 2
```
I don't know the cause yet, but it's random and it was actually first time I saw it.

**Comment by wjdp** [comment]
Thanks for the report, can you post your config as well.

**Comment by miltador** [comment]
My config is:
```
DirectoryPath: '_site'
CheckExternal: false
CheckInternalHash: true
IgnoreInternalEmptyHash: true
IgnoreDirectoryMissingTrailingSlash: true
IgnoreDirs:
- 'tools/pdfjs'
IgnoreURLs:
- 'localhost'
- 'open.cinegy.com'
- 'open.munich.cinegy.local'
- '1(?:[79]2|0)\.(1?68|0)\.\b(?:(?:2(?:[0-4][0-9]|5[0-5])|[0-1]?[0-9]?[0-9])\.){1}(?:(?:2([0-4][0-9]|5[0-4])|[0-1]?[0-9]?[0-9]))\b'
```

**Comment by wjdp** [comment]
I've had a dig around the function that's causing this crash but not finding anything obvious. How often have you seen this output?

**Comment by miltador** [comment]
I get this output about once per 10 runs, today I've got slightly different output indicating another line number:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x50f986]

goroutine 1 [running]:
github.com/wjdp/htmltest/htmldoc.(*Document).Parse(0x0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmldoc/document.go:46 +0x26
github.com/wjdp/htmltest/htmldoc.(*Document).IsHashValid(0x0, 0xc4292f58af, 0xb, 0xc4200b7800)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmldoc/document.go:106 +0x2b
github.com/wjdp/htmltest/htmltest.(*HTMLTest).checkInternalHash(0xc4200b7680, 0xc426057800)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/check-link.go:292 +0xbb
github.com/wjdp/htmltest/htmltest.(*HTMLTest).checkInternal(0xc4200b7680, 0xc426057800)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/check-link.go:266 +0xe9
github.com/wjdp/htmltest/htmltest.(*HTMLTest).checkLink(0xc4200b7680, 0xc420493c70, 0xc4291c02a0)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/check-link.go:91 +0x419
github.com/wjdp/htmltest/htmltest.(*HTMLTest).testDocument(0xc4200b7680, 0xc420493c70)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:197 +0x165
github.com/wjdp/htmltest/htmltest.(*HTMLTest).testDocuments(0xc4200b7680)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:181 +0x69
github.com/wjdp/htmltest/htmltest.Test(0xc420019fb0, 0x1, 0x1, 0x49)
	/home/travis/gopath/src/github.com/wjdp/htmltest/htmltest/htmltest.go:141 +0xb2e
main.run(0xc420019fb0, 0x7ffd3c800b5e)
	/home/travis/gopath/src/github.com/wjdp/htmltest/main.go:155 +0x29e
main.main()
	/home/travis/gopath/src/github.com/wjdp/htmltest/main.go:62 +0x1c1
Process exited with code 2
```

**Comment by miltador** [comment]
I see it now literally each build on our CI. I am not sure I can easily detect the file it's failing on cause we've got 1.5k+ html files.

**Comment by wjdp** [comment]
I've added a debug message that prints:

`testDocument on path.html` right at the start of the tests for a document.

The build that has this is located here: https://builds.htmltest.wjdp.uk/v0.5.0-4-g7d4d1ae/

If you run your tests with log level set to debug: `-l0` you'll be able to spot which document is causing the issue. (Really hoping it's not random 😄)

**Comment by miltador** [comment]
So, here it is. With the debug log I found the html file that causes segfault:
[htmltest_panic.zip](https://github.com/wjdp/htmltest/files/1333614/htmltest_panic.zip)
It is processed fine with `html-proofer` though.

**Comment by wjdp** [comment]
Fabulous, thanks very much for this! I'll try and have a look soon.

**Comment by wjdp** [comment]
Not checked it myself yet but @Manawasp has put forward a fix for this. 

I've merged and the build with this in can be downloaded here https://builds.htmltest.wjdp.uk/v0.6.0-3-gaf7a7d3/, @miltador would you mind checking this works for you? I'll close this issue once we have consensus that this issue is fixed.

**Comment by miltador** [comment]
I confirm the issue is fixed. Thanks all. Waiting for new release :-)
